<!DOCTYPE html>
<html>
<head>
<h1 style="text-align:left;">Logi sisse</h1>
<form action="">
Nimi:<br>
<input name="loginEmail" type="email">
<br>
E-mail:<br>
<input name="loginPassword" type="password">
</form>

<input type = "submit" name = "submitAccount" value = "Kinnita">

<h1>Registreeri kasutaja</h1>
<form action="">
Nimi:<br>
<input name="signupFirstName" type="text">
<br>
Perekonnanimi:<br>
<input name="signupFamilyName" type="text">
<br>
M või N:<br>
<input type="radio" name="gender" value="1">
<input type="radio" name="gender" value="2">
</form>
<input type = "submit" name = "submitAccount" value = "Kinnita">

</head>
<body></body>




</html>