<?php

	
	
	?>


<!DOCTYPE html>
<html>

 <head>
  <meta charset="utf-8">
   <title>1. test</title>
   <link href="https://fonts.googleapis.com/css?family=Crimson+Text:400,400i,600,600i,700,700i" rel="stylesheet">
   <link rel="stylesheet" type="text/css" href="css/style.css">
 </head>

 <body>
  <h1>
	
  1. test</h1>
  <p>See leht on loodud õppetöö raames ja ei sisalda mingit usaldusväärset sisu</p>
  <p>This page is created for study and does not consist anything reliable</p>
  <p><strong>Minu nimi on Kaidi-Liis ja ma astusin see aasta sisse informaatika erialale.</strong></p>
  
	
	<p>Meie õpime <a href = "http://www.tlu.ee"> Tallinna Ülikoolis</a>.</p>
	<p>Minu esimene PHP leht asub <a href = "../esimene.PHP">siin</a>.</p>
	<p>Minu sõbra Timi leht asub <a href = "../../../~jaantim/veebiproge">siin</a>.</p>
	<p>Pilte näeb <a href = "foto.PHP">siin</a>.</p>
 </body>

</html>